services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "3001:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - ncm_api
    environment:
      - VUE_APP_NETEASE_API_URL=http://ncm_api:3000
      - VITE_ELECTRON_API_URL=/api
      - VITE_NETEASE_API_URL=/api
      - VITE_ELECTRON_API_URL_DEV=http://ncm_api:3000
      - VUE_APP_LASTFM_API_KEY=09c55292403d961aa517ff7f5e8a3d9c
      - VUE_APP_LASTFM_API_SHARED_SECRET=307c9fda32b3904e53654baff215cb67
    networks:
      - yesplaymusic_network    

  ncm_api:
    image: ncm-api:v1.0
    ports:
      - "3000:3000"
    networks:
      - yesplaymusic_network

networks:
  yesplaymusic_network:
    driver: bridge